name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        nim: [stable, 2.0.14]
    steps:
    - uses: actions/checkout@v6
    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.nim }}
    - name: Build
      run: nimble install -y --maximumtaggedversions=2
    - name: Test
      run: nimble test -y
